all:
	make ex1
	make ex2
	make ex3

ex1: ex1.c
	gcc -o ex1 ex1.c -Wall -ansi
ex2: ex1.c
	gcc -o ex2 ex2.c -Wall -ansi
ex3: ex1.c
	gcc -o ex3 ex3.c -Wall -ansi

clean: 
	rm ex1
	rm ex2
	rm ex3