all:
	make ex1
	make ex2
	make ex3
	make ex4
	make ex5

ex1: ex1.c
	gcc -o ex1 ex1.c -Wall -ansi
ex2: EX2.c
	gcc -o ex2 ex2.c -Wall -ansi
ex3: ex3.c
	gcc -o ex3 ex3.c -Wall -ansi
ex4: ex4.c
	gcc -o ex4 ex4.c -Wall -ansi
ex5: ex5.c
	gcc -o ex5 ex5.c -Wall -ansi

clean: 
	rm ex1
	rm ex2
	rm ex3
	rm ex4
	rm ex5
